# Generated by Django 5.0 on 2023-12-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_user_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
