# Generated by Django 5.0 on 2023-12-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_order_shipped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=200),
        ),
    ]
