# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: home.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhome.proto\x12\x0eshoppy_backend\"i\n\x0bProductData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"(\n\x0c\x43\x61tegoryData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"o\n\x0cHomePageData\x12-\n\x08products\x18\x01 \x03(\x0b\x32\x1b.shoppy_backend.ProductData\x12\x30\n\ncategories\x18\x02 \x03(\x0b\x32\x1c.shoppy_backend.CategoryData\"\x16\n\x14\x46\x65tchHomePageRequest\"\x17\n\x15\x46\x65tchAboutPageRequest\"H\n\x1bSendContactUsMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"d\n\x15\x46\x65tchHomePageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12*\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1c.shoppy_backend.HomePageData\"G\n\x16\x46\x65tchAboutPageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"M\n\x1cSendContactUsMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\xc8\x02\n\x0eHomeOperations\x12^\n\rFetchHomePage\x12$.shoppy_backend.FetchHomePageRequest\x1a%.shoppy_backend.FetchHomePageResponse\"\x00\x12\x61\n\x0e\x46\x65tchAboutPage\x12%.shoppy_backend.FetchAboutPageRequest\x1a&.shoppy_backend.FetchAboutPageResponse\"\x00\x12s\n\x14SendContactUsMessage\x12+.shoppy_backend.SendContactUsMessageRequest\x1a,.shoppy_backend.SendContactUsMessageResponse\"\x00\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'home_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_PRODUCTDATA']._serialized_start=30
  _globals['_PRODUCTDATA']._serialized_end=135
  _globals['_CATEGORYDATA']._serialized_start=137
  _globals['_CATEGORYDATA']._serialized_end=177
  _globals['_HOMEPAGEDATA']._serialized_start=179
  _globals['_HOMEPAGEDATA']._serialized_end=290
  _globals['_FETCHHOMEPAGEREQUEST']._serialized_start=292
  _globals['_FETCHHOMEPAGEREQUEST']._serialized_end=314
  _globals['_FETCHABOUTPAGEREQUEST']._serialized_start=316
  _globals['_FETCHABOUTPAGEREQUEST']._serialized_end=339
  _globals['_SENDCONTACTUSMESSAGEREQUEST']._serialized_start=341
  _globals['_SENDCONTACTUSMESSAGEREQUEST']._serialized_end=413
  _globals['_FETCHHOMEPAGERESPONSE']._serialized_start=415
  _globals['_FETCHHOMEPAGERESPONSE']._serialized_end=515
  _globals['_FETCHABOUTPAGERESPONSE']._serialized_start=517
  _globals['_FETCHABOUTPAGERESPONSE']._serialized_end=588
  _globals['_SENDCONTACTUSMESSAGERESPONSE']._serialized_start=590
  _globals['_SENDCONTACTUSMESSAGERESPONSE']._serialized_end=667
  _globals['_HOMEOPERATIONS']._serialized_start=670
  _globals['_HOMEOPERATIONS']._serialized_end=998
# @@protoc_insertion_point(module_scope)
