# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dashboard.api.home_pb2 as home__pb2


class HomeOperationsStub(object):
    """*
    Services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchHomePage = channel.unary_unary(
                '/shoppy_backend.HomeOperations/FetchHomePage',
                request_serializer=home__pb2.FetchHomePageRequest.SerializeToString,
                response_deserializer=home__pb2.FetchHomePageResponse.FromString,
                )
        self.FetchAboutPage = channel.unary_unary(
                '/shoppy_backend.HomeOperations/FetchAboutPage',
                request_serializer=home__pb2.FetchAboutPageRequest.SerializeToString,
                response_deserializer=home__pb2.FetchAboutPageResponse.FromString,
                )
        self.SendContactUsMessage = channel.unary_unary(
                '/shoppy_backend.HomeOperations/SendContactUsMessage',
                request_serializer=home__pb2.SendContactUsMessageRequest.SerializeToString,
                response_deserializer=home__pb2.SendContactUsMessageResponse.FromString,
                )


class HomeOperationsServicer(object):
    """*
    Services
    """

    def FetchHomePage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAboutPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendContactUsMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HomeOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchHomePage': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchHomePage,
                    request_deserializer=home__pb2.FetchHomePageRequest.FromString,
                    response_serializer=home__pb2.FetchHomePageResponse.SerializeToString,
            ),
            'FetchAboutPage': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAboutPage,
                    request_deserializer=home__pb2.FetchAboutPageRequest.FromString,
                    response_serializer=home__pb2.FetchAboutPageResponse.SerializeToString,
            ),
            'SendContactUsMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendContactUsMessage,
                    request_deserializer=home__pb2.SendContactUsMessageRequest.FromString,
                    response_serializer=home__pb2.SendContactUsMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shoppy_backend.HomeOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HomeOperations(object):
    """*
    Services
    """

    @staticmethod
    def FetchHomePage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppy_backend.HomeOperations/FetchHomePage',
            home__pb2.FetchHomePageRequest.SerializeToString,
            home__pb2.FetchHomePageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchAboutPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppy_backend.HomeOperations/FetchAboutPage',
            home__pb2.FetchAboutPageRequest.SerializeToString,
            home__pb2.FetchAboutPageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendContactUsMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppy_backend.HomeOperations/SendContactUsMessage',
            home__pb2.SendContactUsMessageRequest.SerializeToString,
            home__pb2.SendContactUsMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
