# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x0eshoppy_backend\"k\n\rProductEntity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"*\n\x0e\x43\x61tegoryEntity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x86\x01\n\x10ProductsPageData\x12/\n\x08products\x18\x01 \x03(\x0b\x32\x1d.shoppy_backend.ProductEntity\x12\x32\n\ncategories\x18\x02 \x03(\x0b\x32\x1e.shoppy_backend.CategoryEntity\x12\r\n\x05pages\x18\x03 \x01(\x05\"Q\n\x14\x46\x65tchProductsRequest\x12\x13\n\x0b\x63\x61tegory_id\x18\x02 \x01(\x05\x12\x16\n\x0esearch_keyword\x18\x03 \x01(\t\x12\x0c\n\x04page\x18\x04 \x01(\x05\"!\n\x13\x46\x65tchProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"h\n\x15\x46\x65tchProductsResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32 .shoppy_backend.ProductsPageData\"d\n\x14\x46\x65tchProductResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12+\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1d.shoppy_backend.ProductEntity2\xd0\x01\n\x11ProductOperations\x12^\n\rFetchProducts\x12$.shoppy_backend.FetchProductsRequest\x1a%.shoppy_backend.FetchProductsResponse\"\x00\x12[\n\x0c\x46\x65tchProduct\x12#.shoppy_backend.FetchProductRequest\x1a$.shoppy_backend.FetchProductResponse\"\x00\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_PRODUCTENTITY']._serialized_start=34
  _globals['_PRODUCTENTITY']._serialized_end=141
  _globals['_CATEGORYENTITY']._serialized_start=143
  _globals['_CATEGORYENTITY']._serialized_end=185
  _globals['_PRODUCTSPAGEDATA']._serialized_start=188
  _globals['_PRODUCTSPAGEDATA']._serialized_end=322
  _globals['_FETCHPRODUCTSREQUEST']._serialized_start=324
  _globals['_FETCHPRODUCTSREQUEST']._serialized_end=405
  _globals['_FETCHPRODUCTREQUEST']._serialized_start=407
  _globals['_FETCHPRODUCTREQUEST']._serialized_end=440
  _globals['_FETCHPRODUCTSRESPONSE']._serialized_start=442
  _globals['_FETCHPRODUCTSRESPONSE']._serialized_end=546
  _globals['_FETCHPRODUCTRESPONSE']._serialized_start=548
  _globals['_FETCHPRODUCTRESPONSE']._serialized_end=648
  _globals['_PRODUCTOPERATIONS']._serialized_start=651
  _globals['_PRODUCTOPERATIONS']._serialized_end=859
# @@protoc_insertion_point(module_scope)
