# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x0eshoppy_backend\"V\n\x08UserData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"\x1f\n\x0eGetUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"S\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"_\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"Z\n\x0fGetUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x18.shoppy_backend.UserData\"]\n\x12\x43reateUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x18.shoppy_backend.UserData\"]\n\x12UpdateUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x18.shoppy_backend.UserData2\x8c\x02\n\x0eUserOperations\x12L\n\x07GetUser\x12\x1e.shoppy_backend.GetUserRequest\x1a\x1f.shoppy_backend.GetUserResponse\"\x00\x12U\n\nCreateUser\x12!.shoppy_backend.CreateUserRequest\x1a\".shoppy_backend.CreateUserResponse\"\x00\x12U\n\nUpdateUser\x12!.shoppy_backend.UpdateUserRequest\x1a\".shoppy_backend.UpdateUserResponse\"\x00\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_USERDATA']._serialized_start=31
  _globals['_USERDATA']._serialized_end=117
  _globals['_GETUSERREQUEST']._serialized_start=119
  _globals['_GETUSERREQUEST']._serialized_end=150
  _globals['_CREATEUSERREQUEST']._serialized_start=152
  _globals['_CREATEUSERREQUEST']._serialized_end=235
  _globals['_UPDATEUSERREQUEST']._serialized_start=237
  _globals['_UPDATEUSERREQUEST']._serialized_end=332
  _globals['_GETUSERRESPONSE']._serialized_start=334
  _globals['_GETUSERRESPONSE']._serialized_end=424
  _globals['_CREATEUSERRESPONSE']._serialized_start=426
  _globals['_CREATEUSERRESPONSE']._serialized_end=519
  _globals['_UPDATEUSERRESPONSE']._serialized_start=521
  _globals['_UPDATEUSERRESPONSE']._serialized_end=614
  _globals['_USEROPERATIONS']._serialized_start=617
  _globals['_USEROPERATIONS']._serialized_end=885
# @@protoc_insertion_point(module_scope)
